::set INSTALLER_ROOT=%~dp0
SET INSTALLER_ROOT=d:\iss
SET /p INSTALLER_ROOT="Enter installer root (%INSTALLER_ROOT%):" %=%

SET INSTALLER_APP=%INSTALLER_ROOT%\%APP_NAME%

SET WHEELS_TARGET=%INSTALLER_ROOT%\wheels
